import { useState } from 'react';
import { RoleBadge, RoleCard } from '../components/Common';

export default function CreatorView({ users, loggedUser, search, setSearch, formatDate, onReset }) {
  const [notice, setNotice] = useState(null);
  const [drafts, setDrafts] = useState({});
  const [expandedUserId, setExpandedUserId] = useState(null);
  const filtered = users.filter((user) => `${user.username || ''} ${user.name}`.toLowerCase().includes(search.toLowerCase()));
  const getToken = () => JSON.parse(localStorage.getItem('forum-demo-session') || '{}')?.token || '';
  const updateAccount = async (user) => {
    const payload = drafts[user.id] || {};
    const response = await fetch(`/api/users/${user.id}/account`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${getToken()}` }, body: JSON.stringify({ email: payload.email ?? user.email ?? '', password: payload.password ?? '' }) });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) return setNotice(result.message || 'No se pudo actualizar la cuenta.');
    setNotice(`Cuenta de ${user.username} actualizada.`); setDrafts((current) => ({ ...current, [user.id]: {} })); window.location.reload();
  };
  const deleteUser = async (user) => { if (user.id === loggedUser.id) return; await fetch(`/api/creator/users/${user.id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${getToken()}` } }); window.location.reload(); };
  return <section className="page-view"><div className="page-heading"><div><p className="eyebrow">Acceso de propietario</p><h2>Panel de creación</h2><small>Las contraseñas se almacenan como hashes.</small></div><RoleBadge role="creator" /></div><div className="panel-card creator-danger-zone"><p className="mini-label">Base de datos</p><h3>Reinicio completo</h3><p>Elimina usuarios, contenido y tickets, conservando esta cuenta creadora.</p><button className="danger-btn" onClick={onReset}>Reiniciar datos</button></div><div className="panel-card"><div className="panel-toolbar"><div><p className="mini-label">Cuentas</p><h3>Gestionar usuarios</h3></div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por @username" /></div><div className="admin-list">{filtered.map((user) => <div className="admin-user-row creator-user-row" key={user.id}><RoleCard user={user} meta={user.email || 'Correo privado'} /><div className="creator-controls"><button className="mini-action" onClick={() => setExpandedUserId((current) => current === user.id ? null : user.id)}>{expandedUserId === user.id ? 'Ocultar información' : 'Ver información'}</button><input value={drafts[user.id]?.email ?? user.email ?? ''} onChange={(event) => setDrafts((current) => ({ ...current, [user.id]: { ...current[user.id], email: event.target.value } }))} placeholder="Correo nuevo" /><input type="password" value={drafts[user.id]?.password ?? ''} onChange={(event) => setDrafts((current) => ({ ...current, [user.id]: { ...current[user.id], password: event.target.value } }))} placeholder="Contraseña nueva" /><button className="mini-action" onClick={() => updateAccount(user)}>Guardar cuenta</button><button className="mini-action danger-text" disabled={user.id === loggedUser.id} onClick={() => deleteUser(user)}>Eliminar cuenta</button></div>{expandedUserId === user.id && <dl className="account-details"><div><dt>ID público</dt><dd>{user.publicId || user.id}</dd></div><div><dt>Display name</dt><dd>{user.name}</dd></div><div><dt>Username</dt><dd>{user.username}</dd></div><div><dt>Correo</dt><dd>{user.email || 'Privado'}</dd></div><div><dt>Rol</dt><dd>{user.role}</dd></div><div><dt>Estado</dt><dd>{user.status}</dd></div><div><dt>Creada</dt><dd>{user.createdAt ? formatDate(user.createdAt) : 'No disponible'}</dd></div><div className="account-details-wide"><dt>Contraseña actual</dt><dd>Protegida mediante hash; se puede reemplazar, no consultar.</dd></div></dl>}</div>)}</div>{notice && <p className="empty-state">{notice}</p>}</div></section>;
}
