import { RoleCard } from '../components/Common';

export default function ModerationView({ users, reports, hiddenPosts, userMap, loggedUser, onOpenSanction, onHide, onDelete, onResolveReport, formatDate }) {
  return <section className="page-view"><div className="page-heading"><div><p className="eyebrow">Control de comunidad</p><h2>Panel de moderación</h2></div><span className="role-badge role-moderator">Moderador</span></div><div className="panel-card"><p className="mini-label">Usuarios y sanciones</p><div className="admin-list">{users.filter((user) => user.id !== loggedUser.id).map((user) => <ModerationUserRow key={user.id} user={user} onOpenSanction={onOpenSanction} formatDate={formatDate} />)}</div></div><div className="panel-card"><p className="mini-label">Reportes abiertos</p>{reports.length ? <div className="admin-list">{reports.map((report) => <div className="moderation-item" key={report.id}><div><strong>{report.targetType === 'thread' ? 'Publicación' : 'Respuesta'} reportada</strong><small>{report.reason} · por {report.reporterUsername}</small></div><div className="action-row"><button className="mini-action" onClick={() => onResolveReport(report.id, 'dismissed')}>Descartar</button><button className="mini-action danger-text" onClick={() => onResolveReport(report.id, 'resolved')}>Resolver</button></div></div>)}</div> : <p className="empty-state">No hay reportes pendientes.</p>}</div><div className="panel-card"><p className="mini-label">Contenido oculto</p>{hiddenPosts.length ? hiddenPosts.map((post) => <div className="moderation-item" key={post.id}><div><strong>{userMap[post.authorId]?.name}</strong><small>{post.content}</small></div><div className="action-row"><button className="mini-action" onClick={() => onHide(post)}>Mostrar</button><button className="mini-action danger-text" onClick={() => onDelete(post)}>Eliminar</button></div></div>) : <p className="empty-state">No hay contenido oculto.</p>}</div></section>;
}

function ModerationUserRow({ user, onOpenSanction, formatDate }) {
  const statusText = user.status === 'banned' ? `Suspendido${user.bannedUntil ? ` hasta ${formatDate(user.bannedUntil)}` : ''}` : user.mutedUntil ? `Silenciado hasta ${formatDate(user.mutedUntil)}` : 'Activo';
  return <div className="admin-user-row moderation-user-row"><RoleCard user={user} meta={statusText} /><div className="moderation-controls"><button className="mini-action" onClick={() => onOpenSanction(user, 'mute')}>{user.mutedUntil ? 'Cambiar mute' : 'Silenciar'}</button><button className="mini-action danger-text" onClick={() => onOpenSanction(user, 'ban')}>{user.status === 'banned' ? 'Cambiar ban' : 'Banear'}</button></div></div>;
}
